# Generated by Django 4.2.30 on 2026-06-05 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('area_id', models.AutoField(db_column='Area_id', db_comment='ID', primary_key=True, serialize=False)),
                ('area_name', models.CharField(blank=True, db_column='Area_name', db_comment='Название района', max_length=200, null=True, unique=True)),
            ],
            options={
                'db_table': 'Areas',
                'db_table_comment': 'Районы',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyname', models.CharField(blank=True, db_column='CompanyName', db_comment='Название', max_length=150, null=True)),
                ('address', models.CharField(blank=True, db_comment='Адрес', max_length=150, null=True)),
                ('telephones', models.CharField(blank=True, db_column='Telephones', db_comment='Телефоны', max_length=100, null=True)),
                ('director', models.CharField(blank=True, db_column='Director', db_comment='Директор', max_length=150, null=True)),
                ('director2', models.CharField(blank=True, db_column='Director2', db_comment='Ответственный', max_length=150, null=True)),
                ('computer', models.CharField(blank=True, db_column='Computer', db_comment='Имя компьютера, на котором изм', max_length=100, null=True)),
                ('memo', models.CharField(blank=True, db_column='Memo', db_comment='Дополнительная информация', max_length=7000, null=True)),
                ('lasteditdate', models.DateTimeField(blank=True, db_column='LastEditDate', db_comment='Дата последнего изменения запи', null=True)),
                ('company_id', models.CharField(db_comment='ID', max_length=18, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='UserName', db_comment='Имя пользователя, который изме', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Company',
                'db_table_comment': 'Плательщик',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('organization', models.CharField(blank=True, db_column='Organization', max_length=500, null=True)),
                ('organizationaddress', models.CharField(blank=True, db_column='OrganizationAddress', max_length=500, null=True)),
                ('director', models.CharField(blank=True, db_column='Director', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Installers',
            fields=[
                ('installer_id', models.AutoField(db_column='Installer_id', db_comment='ID', primary_key=True, serialize=False)),
                ('installername', models.CharField(db_column='InstallerName', db_comment='ФИО монтажника', max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Installers',
                'db_table_comment': 'Ответственные монтажники',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('master_id', models.AutoField(db_column='Master_id', db_comment='ID', primary_key=True, serialize=False)),
                ('mastername', models.CharField(db_column='MasterName', db_comment='ФИО мастера', max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Masters',
                'db_table_comment': 'Ответственные мастера',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('panel_id', models.CharField(db_column='Panel_id', db_comment='Номер объекта', max_length=15, primary_key=True, serialize=False)),
                ('password_field', models.CharField(blank=True, db_column='Password_', db_comment='Пароль', max_length=12, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', db_comment='Дата создания', null=True)),
                ('disabled', models.BooleanField(db_column='Disabled', db_comment='1 - Объект отключен')),
                ('remarks', models.CharField(blank=True, db_column='Remarks', db_comment='Тип сигнализации', max_length=100, null=True)),
                ('computer', models.CharField(blank=True, db_comment='Имя компьютера, на котором изм', max_length=50, null=True)),
                ('datelastchange', models.DateTimeField(blank=True, db_column='DateLastChange', db_comment='Дата последнего изменения данн', null=True)),
                ('engineer_id', models.IntegerField(blank=True, db_comment='engineers.engineer_id', null=True)),
                ('additionaltechnicalinformation', models.CharField(blank=True, db_column='AdditionalTechnicalInformation', db_comment='Дополнительная техническая инф', max_length=2000, null=True)),
                ('onetestequalall', models.BooleanField(db_column='OneTestEqualAll', db_comment='Приход теста от любого прибора')),
                ('compediting', models.CharField(blank=True, db_column='CompEditing', db_comment='Имя компьютера, на котором дан', max_length=20, null=True)),
                ('testpanel', models.BooleanField(db_column='TestPanel', db_comment='1 - Постоянный стенд')),
                ('partial', models.CharField(blank=True, db_column='Partial', db_comment='Частичные отключения', max_length=500, null=True)),
                ('latitude', models.CharField(blank=True, db_column='Latitude', db_comment='GPS координаты - Широта', max_length=20, null=True)),
                ('longtitude', models.CharField(blank=True, db_column='Longtitude', db_comment='GPS координаты - Долгота', max_length=20, null=True)),
                ('isgpsconfirm', models.BooleanField(db_column='isGPSConfirm', db_comment='GPS координаты подтверждены')),
                ('complasteditgps', models.CharField(blank=True, db_column='CompLastEditGPS', db_comment='Имя компьютера, на котором изм', max_length=70, null=True)),
                ('engine', models.BooleanField(db_column='Engine', db_comment='Для подвижного объекта состоян')),
                ('track', models.IntegerField(db_column='Track', db_comment='vwPanelMobileGPS.TrackID')),
                ('isalwayssendgps', models.BooleanField(db_column='isAlwaysSendGPS', db_comment='Объект постоянно шлет GPS коор')),
                ('movable_object', models.BooleanField(db_column='Movable_Object', db_comment='1 - подвижный объект')),
                ('panel_type', models.SmallIntegerField(db_column='Panel_type', db_comment='1 - пожарный объект')),
                ('pult_id', models.IntegerField(blank=True, db_column='Pult_id', db_comment='Pults.Pult_id', null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', db_comment='Имя пользователя, который изме', max_length=200, null=True)),
                ('regionid', models.IntegerField(blank=True, db_column='RegionID', db_comment='RegionsTable.RegionID', null=True)),
                ('iscontactidredirect', models.BooleanField(db_column='IsContactIDRedirect')),
                ('contactidobjectnumber', models.CharField(blank=True, db_column='ContactIDObjectNumber', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Panel',
                'db_table_comment': 'Объекты',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pults',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('pult_name', models.CharField(blank=True, db_column='Pult_Name', max_length=500, null=True, unique=True)),
                ('pult_director', models.CharField(blank=True, db_column='Pult_Director', max_length=300, null=True)),
                ('pult_adres', models.CharField(blank=True, db_column='Pult_Adres', max_length=300, null=True)),
                ('pult_phone', models.CharField(blank=True, db_column='Pult_Phone', max_length=500, null=True)),
                ('pult_description', models.CharField(blank=True, db_column='Pult_Description', max_length=1000, null=True)),
                ('pult_idnumber', models.CharField(blank=True, db_column='Pult_IDNumber', max_length=50, null=True)),
                ('res_name', models.CharField(blank=True, db_column='RES_Name', max_length=300, null=True)),
                ('res_address', models.CharField(blank=True, db_column='RES_Address', max_length=300, null=True)),
                ('res_phone', models.CharField(blank=True, db_column='RES_Phone', max_length=300, null=True)),
            ],
            options={
                'db_table': 'Pults',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serviceorganization',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('servicename', models.CharField(db_column='ServiceName', max_length=500, unique=True)),
                ('idcode', models.CharField(blank=True, db_column='IDCode', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ServiceOrganization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('panel', models.OneToOneField(db_column='Panel_id', db_comment='Panel.Panel_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pult4db.panel')),
                ('group_field', models.IntegerField(db_column='Group_', db_comment='Номер')),
                ('message', models.CharField(db_column='Message', db_comment='Описание', max_length=100)),
                ('isopen', models.BooleanField(blank=True, db_column='IsOpen', db_comment='Группа под охраной: 0 - да; 1 ', null=True)),
                ('timeevent', models.DateTimeField(blank=True, db_column='TimeEvent', db_comment='Время прихода последнего событ', null=True)),
                ('opencontrol', models.BooleanField(blank=True, db_column='OpenControl', db_comment='1 - Контроль открытий по распи', null=True)),
                ('z8timeout', models.DateTimeField(blank=True, db_column='Z8Timeout', db_comment='Ожидание звонка с объекта при ', null=True)),
                ('typeschedule', models.IntegerField(blank=True, db_column='typeSchedule', db_comment='Тип работы группы: 1 - свободн', null=True)),
                ('armedcall', models.BooleanField(blank=True, db_column='ArmedCall', db_comment='Ставятся под охрану по звонку:', null=True)),
                ('disabled', models.BooleanField(blank=True, db_comment='Группа отключена', null=True)),
                ('mustcall', models.BooleanField(blank=True, db_column='mustCall', db_comment='Обязательный прозвон, при нару', null=True)),
                ('timeforclose', models.DateTimeField(blank=True, db_column='TimeForClose', db_comment='Контроль закрытий круглосуточн', null=True)),
                ('partial', models.CharField(blank=True, db_column='Partial', db_comment='Не используется', max_length=150, null=True)),
                ('operatorprompt', models.CharField(blank=True, db_column='OperatorPrompt', db_comment='Инструкция по реагированию для', max_length=2000, null=True)),
                ('isprohibited', models.BooleanField(blank=True, db_column='IsProhibited', db_comment='Признак запрет постановки для ', null=True)),
                ('autoarmdisarm', models.BooleanField(db_column='AutoArmDisarm')),
                ('alarmbuttonphmk', models.BooleanField(db_column='alarmButtonPhMk')),
                ('isopenbyaccess', models.BooleanField(blank=True, db_column='IsOpenByAccess', null=True)),
                ('intervalpatrolinspection', models.DateTimeField(blank=True, db_column='IntervalPatrolInspection', null=True)),
            ],
            options={
                'db_table': 'Groups',
                'db_table_comment': 'Группы объекта',
                'managed': False,
            },
        ),
    ]
